Primeira merge
NadineLemosA/random-exercises pull request #1
Opened 2023-07-27 21:42 UTC by NadineLemosA

2023-07-27 22:01 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +	Queue<Person> line = new ArrayDeque<>();
Cuidado com o jogo de palavras. As vezes tu usa "Queue" e as vezes tu usa "Line" sendo que são a mesma coisa porém palavras diferentes

2023-07-27 22:25 UTC, zejustinn requested changes

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +	void showTheQueue() {
Tente evitar de utilizar artigos nos nomes de funções e variaveis

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +			System.out.println(p.name);
Remove o "System.out.print"

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +		return result;
Remove a variavel "result"

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +	}
Retornar pessoa

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +	void writeMenuOnScreen() {
Alterar o nome da função

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +		System.out.println("3- CHAMAR PRÓX DA FILA");
Não utilizar abreviações

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +				Person newPerson = new Person(input.next());
Remover prefixo "new"

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			System.out.println(p.name);
Utilizar apenas uma escrita no console

2023-07-27 22:25 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			for (int i = 0; i < listOfPeopleCreated.size(); i++) {
Criar função e reutilizar

2023-07-27 22:31 UTC, NadineLemosA commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +	Queue<Person> line = new ArrayDeque<>();
Certo

2023-07-28 15:17 UTC, NadineLemosA commented on practicingClasses/queueWithPeople/QueueMenu.java
> +		System.out.println("3- CHAMAR PRÓX DA FILA");
Feito

2023-07-29 14:40 UTC, zejustinn requested changes

2023-07-29 14:40 UTC, zejustinn commented on practicingClasses/queueWithPeople/Runnable.java
> +		QueueMenu queueMenu1 = new QueueMenu();
Remover o 1 do nome da variavel

2023-07-29 14:40 UTC, zejustinn commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +		return line.remove(); // isso funciona dessa forma?
Apague o esse comentário. Nunca se comunicar pelo código

2023-07-29 14:40 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			case 1:
Substituir números dos casos para algo mais descritivo. Por exemplo, Enum ou constates

2023-07-29 14:40 UTC, zejustinn commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			for (int i = 0; i < listOfPeopleCreated.size(); i++) {
Responder o motivo de não ter feito a alteração para ter registrado

2023-07-31 21:45 UTC, zejustinn approved these changes

2023-07-31 21:50 UTC, NadineLemosA commented on practicingClasses/queueWithPeople/LineOfPeople.java
> +		return result;
Feito e funcionando. Da uma olhada, por favor.

2023-07-31 21:50 UTC, NadineLemosA commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			for (int i = 0; i < listOfPeopleCreated.size(); i++) {
Embora a maior parte do código faça a mesma coisa nas duas funções, o núcleo realiza coisas diferentes(adição e exclusão de elementos). Por conta disso, decidiu-se que seria melhor deixar dessa forma por enquanto.

2023-07-31 21:50 UTC, NadineLemosA commented on practicingClasses/queueWithPeople/QueueMenu.java
> +			case 1:
Substituído por constantes, pois neste caso, no switch não funciona

2023-07-31 21:53 UTC, merged